version: 0.1.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'
cache:
  - packages -> **\packages.config  
build:
  project: Seq.App.Datadog.sln
before_build:
  - cmd: nuget restore
#   publish_nuget: true
#   publish_nuget_symbols: true
#   verbosity: minimal
# deploy:
# - provider: NuGet
#   api_key:
#     secure: owIruqEXZlFwqcSBYyjR19/8EodS+aXFzZmBwqlaYnDE/uy1X+KsuI5QH3p9iBmx
#   on:
#     branch: master